name: mingly
description: "Elite Networking &  Exclusive Events"
publish_to: "none"

version: 0.3.0-beta+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.1.0
  flutter_svg: ^2.2.0
  flutter_screenutil: ^5.9.3
  avatar_stack: ^3.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  webview_flutter: ^4.13.0
  image_picker: ^1.2.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_html: ^3.0.0
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.2
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  google_sign_in: ^6.2.0
  cloud_firestore: ^6.0.3
  flutter_linkify: ^6.0.0
  get: ^4.7.2
  collection: ^1.19.1
  share_plus: ^12.0.1
  youtube_player_flutter: ^9.1.3
  http: ^1.6.0
  markdown_widget: ^2.3.2+8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: lib/assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Gotham
      fonts:
        - asset: lib/assets/fonts/Gotham-Book.otf
          weight: 400
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/country_city.json
